import "./globals.css";
import { WindowSizeProvider } from "./hooks/WindowSizeContext";
import { jost } from "./fonts";

export const metadata = {
  title: "JEB - Embarquez !",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <WindowSizeProvider>
        <body className={jost.className}>{children}</body>
      </WindowSizeProvider>
    </html>
  );
}
