import { Jost, Londrina_Solid } from "next/font/google";
import "./globals.css";
import { WindowSizeProvider } from "./hooks/WindowSizeContext";

const jost = Jost({
  weight: "100",
  subsets: ["latin"],
  display: "swap",
});

const londrina_solid = Londrina_Solid({
  weight: "300",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "JEB - Embarquez !",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <WindowSizeProvider>
      <html lang="fr">
        <body className={(jost.className, londrina_solid.className)}>
          {children}
        </body>
      </html>
    </WindowSizeProvider>
  );
}
